### ISSUE TITLE
Create links admin page

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#170] opened 2019-09-16 15:24 UTC
At the moment, the creation of new links it is very cumbersome. With the current number of ASes, it's almost impossible to select the two ends of the link.
![image](https://user-images.githubusercontent.com/5399303/64970798-c7d05200-d8a6-11e9-8c3c-012d85fb646b.png)

**Comment by matzf** [comment] 2019-10-03 15:12
Duplicate of #154

**Closed by matzf** 2019-10-03 15:12 UTC
Labels: help wanted
